package com.rzq.gpms.api.calendar.dao;

import com.rzq.gpms.api.calendar.domain.Calendar;
import com.rzq.gpms.api.calendar.domain.CalendarCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int countByExample(CalendarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int deleteByExample(CalendarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int insert(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int insertSelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    List<Calendar> selectByExampleWithRowbounds(CalendarCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    List<Calendar> selectByExample(CalendarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    Calendar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Calendar record, @Param("example") CalendarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Calendar record, @Param("example") CalendarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Calendar record);
}