package com.rzq.gpms.api.rolePage.dao;

import com.rzq.gpms.api.rolePage.domain.RolePage;
import com.rzq.gpms.api.rolePage.domain.RolePageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RolePageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int countByExample(RolePageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int deleteByExample(RolePageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("roleid") Integer roleid, @Param("pageid") Integer pageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int insert(RolePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int insertSelective(RolePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    List<RolePage> selectByExampleWithRowbounds(RolePageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    List<RolePage> selectByExample(RolePageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RolePage record, @Param("example") RolePageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_page
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RolePage record, @Param("example") RolePageCriteria example);
}