package com.rzq.gpms.api.schedule.dao;

import com.rzq.gpms.api.schedule.domain.Schedule;
import com.rzq.gpms.api.schedule.domain.ScheduleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int countByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int deleteByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    List<Schedule> selectByExampleWithRowbounds(ScheduleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    List<Schedule> selectByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    Schedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Schedule record, @Param("example") ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Schedule record, @Param("example") ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schedule record);
}