package com.rzq.gpms.api.roleTree.domain;

import java.io.Serializable;

public class RoleTree implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_tree.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_tree.pageid
     *
     * @mbggenerated
     */
    private Integer pageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_tree
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_tree.roleid
     *
     * @return the value of sys_role_tree.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_tree.roleid
     *
     * @param roleid the value for sys_role_tree.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_tree.pageid
     *
     * @return the value of sys_role_tree.pageid
     *
     * @mbggenerated
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_tree.pageid
     *
     * @param pageid the value for sys_role_tree.pageid
     *
     * @mbggenerated
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_tree
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", pageid=").append(pageid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}