package com.rzq.gpms.api.file.domain;

import java.io.Serializable;
import java.util.Date;

public class File implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_file.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_file.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_file.currentdate
     *
     * @mbggenerated
     */
    private Date currentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_file.ownerid
     *
     * @mbggenerated
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_file.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_file
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_file.id
     *
     * @return the value of man_file.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_file.id
     *
     * @param id the value for man_file.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_file.name
     *
     * @return the value of man_file.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_file.name
     *
     * @param name the value for man_file.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_file.currentdate
     *
     * @return the value of man_file.currentdate
     *
     * @mbggenerated
     */
    public Date getCurrentdate() {
        return currentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_file.currentdate
     *
     * @param currentdate the value for man_file.currentdate
     *
     * @mbggenerated
     */
    public void setCurrentdate(Date currentdate) {
        this.currentdate = currentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_file.ownerid
     *
     * @return the value of man_file.ownerid
     *
     * @mbggenerated
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_file.ownerid
     *
     * @param ownerid the value for man_file.ownerid
     *
     * @mbggenerated
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_file.path
     *
     * @return the value of man_file.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_file.path
     *
     * @param path the value for man_file.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", currentdate=").append(currentdate);
        sb.append(", ownerid=").append(ownerid);
        sb.append(", path=").append(path);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}