package com.rzq.gpms.api.file.dao;

import com.rzq.gpms.api.file.domain.File;
import com.rzq.gpms.api.file.domain.FileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int countByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int deleteByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    List<File> selectByExampleWithRowbounds(FileCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    List<File> selectByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") File record, @Param("example") FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(File record);
}