package com.rzq.gpms.api.page.dao;

import com.rzq.gpms.api.page.domain.Page;
import com.rzq.gpms.api.page.domain.PageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int countByExample(PageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int deleteByExample(PageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int insertSelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    List<Page> selectByExampleWithRowbounds(PageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    List<Page> selectByExample(PageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    Page selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Page record, @Param("example") PageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Page record, @Param("example") PageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Page record);
}