package com.rzq.gpms.api.schedule.domain;

import java.io.Serializable;
import java.util.Date;

public class Schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.currentdate
     *
     * @mbggenerated
     */
    private Date currentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.ownerid
     *
     * @mbggenerated
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.start
     *
     * @mbggenerated
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.end
     *
     * @mbggenerated
     */
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.isfinished
     *
     * @mbggenerated
     */
    private String isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_schedule.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.id
     *
     * @return the value of man_schedule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.id
     *
     * @param id the value for man_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.currentdate
     *
     * @return the value of man_schedule.currentdate
     *
     * @mbggenerated
     */
    public Date getCurrentdate() {
        return currentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.currentdate
     *
     * @param currentdate the value for man_schedule.currentdate
     *
     * @mbggenerated
     */
    public void setCurrentdate(Date currentdate) {
        this.currentdate = currentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.ownerid
     *
     * @return the value of man_schedule.ownerid
     *
     * @mbggenerated
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.ownerid
     *
     * @param ownerid the value for man_schedule.ownerid
     *
     * @mbggenerated
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.start
     *
     * @return the value of man_schedule.start
     *
     * @mbggenerated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.start
     *
     * @param start the value for man_schedule.start
     *
     * @mbggenerated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.end
     *
     * @return the value of man_schedule.end
     *
     * @mbggenerated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.end
     *
     * @param end the value for man_schedule.end
     *
     * @mbggenerated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.content
     *
     * @return the value of man_schedule.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.content
     *
     * @param content the value for man_schedule.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.status
     *
     * @return the value of man_schedule.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.status
     *
     * @param status the value for man_schedule.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.isfinished
     *
     * @return the value of man_schedule.isfinished
     *
     * @mbggenerated
     */
    public String getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.isfinished
     *
     * @param isfinished the value for man_schedule.isfinished
     *
     * @mbggenerated
     */
    public void setIsfinished(String isfinished) {
        this.isfinished = isfinished == null ? null : isfinished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_schedule.location
     *
     * @return the value of man_schedule.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_schedule.location
     *
     * @param location the value for man_schedule.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_schedule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", currentdate=").append(currentdate);
        sb.append(", ownerid=").append(ownerid);
        sb.append(", start=").append(start);
        sb.append(", end=").append(end);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", isfinished=").append(isfinished);
        sb.append(", location=").append(location);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}