package com.rzq.gpms.api.calendar.domain;

import java.util.ArrayList;
import java.util.List;

public class CalendarCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public CalendarCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNull() {
            addCriterion("ownerid is null");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNotNull() {
            addCriterion("ownerid is not null");
            return (Criteria) this;
        }

        public Criteria andOwneridEqualTo(Integer value) {
            addCriterion("ownerid =", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotEqualTo(Integer value) {
            addCriterion("ownerid <>", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThan(Integer value) {
            addCriterion("ownerid >", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ownerid >=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThan(Integer value) {
            addCriterion("ownerid <", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThanOrEqualTo(Integer value) {
            addCriterion("ownerid <=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridIn(List<Integer> values) {
            addCriterion("ownerid in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotIn(List<Integer> values) {
            addCriterion("ownerid not in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridBetween(Integer value1, Integer value2) {
            addCriterion("ownerid between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotBetween(Integer value1, Integer value2) {
            addCriterion("ownerid not between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andStartIsNull() {
            addCriterion("start is null");
            return (Criteria) this;
        }

        public Criteria andStartIsNotNull() {
            addCriterion("start is not null");
            return (Criteria) this;
        }

        public Criteria andStartEqualTo(String value) {
            addCriterion("start =", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotEqualTo(String value) {
            addCriterion("start <>", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartGreaterThan(String value) {
            addCriterion("start >", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartGreaterThanOrEqualTo(String value) {
            addCriterion("start >=", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartLessThan(String value) {
            addCriterion("start <", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartLessThanOrEqualTo(String value) {
            addCriterion("start <=", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartLike(String value) {
            addCriterion("start like", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotLike(String value) {
            addCriterion("start not like", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartIn(List<String> values) {
            addCriterion("start in", values, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotIn(List<String> values) {
            addCriterion("start not in", values, "start");
            return (Criteria) this;
        }

        public Criteria andStartBetween(String value1, String value2) {
            addCriterion("start between", value1, value2, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotBetween(String value1, String value2) {
            addCriterion("start not between", value1, value2, "start");
            return (Criteria) this;
        }

        public Criteria andEndIsNull() {
            addCriterion("end is null");
            return (Criteria) this;
        }

        public Criteria andEndIsNotNull() {
            addCriterion("end is not null");
            return (Criteria) this;
        }

        public Criteria andEndEqualTo(String value) {
            addCriterion("end =", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndNotEqualTo(String value) {
            addCriterion("end <>", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndGreaterThan(String value) {
            addCriterion("end >", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndGreaterThanOrEqualTo(String value) {
            addCriterion("end >=", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndLessThan(String value) {
            addCriterion("end <", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndLessThanOrEqualTo(String value) {
            addCriterion("end <=", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndLike(String value) {
            addCriterion("end like", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndNotLike(String value) {
            addCriterion("end not like", value, "end");
            return (Criteria) this;
        }

        public Criteria andEndIn(List<String> values) {
            addCriterion("end in", values, "end");
            return (Criteria) this;
        }

        public Criteria andEndNotIn(List<String> values) {
            addCriterion("end not in", values, "end");
            return (Criteria) this;
        }

        public Criteria andEndBetween(String value1, String value2) {
            addCriterion("end between", value1, value2, "end");
            return (Criteria) this;
        }

        public Criteria andEndNotBetween(String value1, String value2) {
            addCriterion("end not between", value1, value2, "end");
            return (Criteria) this;
        }

        public Criteria andAlldayIsNull() {
            addCriterion("allDay is null");
            return (Criteria) this;
        }

        public Criteria andAlldayIsNotNull() {
            addCriterion("allDay is not null");
            return (Criteria) this;
        }

        public Criteria andAlldayEqualTo(Boolean value) {
            addCriterion("allDay =", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayNotEqualTo(Boolean value) {
            addCriterion("allDay <>", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayGreaterThan(Boolean value) {
            addCriterion("allDay >", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allDay >=", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayLessThan(Boolean value) {
            addCriterion("allDay <", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayLessThanOrEqualTo(Boolean value) {
            addCriterion("allDay <=", value, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayIn(List<Boolean> values) {
            addCriterion("allDay in", values, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayNotIn(List<Boolean> values) {
            addCriterion("allDay not in", values, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayBetween(Boolean value1, Boolean value2) {
            addCriterion("allDay between", value1, value2, "allday");
            return (Criteria) this;
        }

        public Criteria andAlldayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allDay not between", value1, value2, "allday");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorIsNull() {
            addCriterion("backgroundColor is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorIsNotNull() {
            addCriterion("backgroundColor is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorEqualTo(String value) {
            addCriterion("backgroundColor =", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorNotEqualTo(String value) {
            addCriterion("backgroundColor <>", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorGreaterThan(String value) {
            addCriterion("backgroundColor >", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorGreaterThanOrEqualTo(String value) {
            addCriterion("backgroundColor >=", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorLessThan(String value) {
            addCriterion("backgroundColor <", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorLessThanOrEqualTo(String value) {
            addCriterion("backgroundColor <=", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorLike(String value) {
            addCriterion("backgroundColor like", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorNotLike(String value) {
            addCriterion("backgroundColor not like", value, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorIn(List<String> values) {
            addCriterion("backgroundColor in", values, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorNotIn(List<String> values) {
            addCriterion("backgroundColor not in", values, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorBetween(String value1, String value2) {
            addCriterion("backgroundColor between", value1, value2, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorNotBetween(String value1, String value2) {
            addCriterion("backgroundColor not between", value1, value2, "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorIsNull() {
            addCriterion("borderColor is null");
            return (Criteria) this;
        }

        public Criteria andBordercolorIsNotNull() {
            addCriterion("borderColor is not null");
            return (Criteria) this;
        }

        public Criteria andBordercolorEqualTo(String value) {
            addCriterion("borderColor =", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorNotEqualTo(String value) {
            addCriterion("borderColor <>", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorGreaterThan(String value) {
            addCriterion("borderColor >", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorGreaterThanOrEqualTo(String value) {
            addCriterion("borderColor >=", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorLessThan(String value) {
            addCriterion("borderColor <", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorLessThanOrEqualTo(String value) {
            addCriterion("borderColor <=", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorLike(String value) {
            addCriterion("borderColor like", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorNotLike(String value) {
            addCriterion("borderColor not like", value, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorIn(List<String> values) {
            addCriterion("borderColor in", values, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorNotIn(List<String> values) {
            addCriterion("borderColor not in", values, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorBetween(String value1, String value2) {
            addCriterion("borderColor between", value1, value2, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorNotBetween(String value1, String value2) {
            addCriterion("borderColor not between", value1, value2, "bordercolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorIsNull() {
            addCriterion("textColor is null");
            return (Criteria) this;
        }

        public Criteria andTextcolorIsNotNull() {
            addCriterion("textColor is not null");
            return (Criteria) this;
        }

        public Criteria andTextcolorEqualTo(String value) {
            addCriterion("textColor =", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorNotEqualTo(String value) {
            addCriterion("textColor <>", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorGreaterThan(String value) {
            addCriterion("textColor >", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorGreaterThanOrEqualTo(String value) {
            addCriterion("textColor >=", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorLessThan(String value) {
            addCriterion("textColor <", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorLessThanOrEqualTo(String value) {
            addCriterion("textColor <=", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorLike(String value) {
            addCriterion("textColor like", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorNotLike(String value) {
            addCriterion("textColor not like", value, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorIn(List<String> values) {
            addCriterion("textColor in", values, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorNotIn(List<String> values) {
            addCriterion("textColor not in", values, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorBetween(String value1, String value2) {
            addCriterion("textColor between", value1, value2, "textcolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorNotBetween(String value1, String value2) {
            addCriterion("textColor not between", value1, value2, "textcolor");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTitleLikeInsensitive(String value) {
            addCriterion("upper(title) like", value.toUpperCase(), "title");
            return (Criteria) this;
        }

        public Criteria andStartLikeInsensitive(String value) {
            addCriterion("upper(start) like", value.toUpperCase(), "start");
            return (Criteria) this;
        }

        public Criteria andEndLikeInsensitive(String value) {
            addCriterion("upper(end) like", value.toUpperCase(), "end");
            return (Criteria) this;
        }

        public Criteria andColorLikeInsensitive(String value) {
            addCriterion("upper(color) like", value.toUpperCase(), "color");
            return (Criteria) this;
        }

        public Criteria andBackgroundcolorLikeInsensitive(String value) {
            addCriterion("upper(backgroundColor) like", value.toUpperCase(), "backgroundcolor");
            return (Criteria) this;
        }

        public Criteria andBordercolorLikeInsensitive(String value) {
            addCriterion("upper(borderColor) like", value.toUpperCase(), "bordercolor");
            return (Criteria) this;
        }

        public Criteria andTextcolorLikeInsensitive(String value) {
            addCriterion("upper(textColor) like", value.toUpperCase(), "textcolor");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_calendar
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}