package com.rzq.gpms.api.calendar.domain;

import java.io.Serializable;

public class Calendar implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.ownerid
     *
     * @mbggenerated
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.start
     *
     * @mbggenerated
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.end
     *
     * @mbggenerated
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.allDay
     *
     * @mbggenerated
     */
    private Boolean allday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.backgroundColor
     *
     * @mbggenerated
     */
    private String backgroundcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.borderColor
     *
     * @mbggenerated
     */
    private String bordercolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.textColor
     *
     * @mbggenerated
     */
    private String textcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_calendar.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.id
     *
     * @return the value of man_calendar.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.id
     *
     * @param id the value for man_calendar.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.title
     *
     * @return the value of man_calendar.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.title
     *
     * @param title the value for man_calendar.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.ownerid
     *
     * @return the value of man_calendar.ownerid
     *
     * @mbggenerated
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.ownerid
     *
     * @param ownerid the value for man_calendar.ownerid
     *
     * @mbggenerated
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.start
     *
     * @return the value of man_calendar.start
     *
     * @mbggenerated
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.start
     *
     * @param start the value for man_calendar.start
     *
     * @mbggenerated
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.end
     *
     * @return the value of man_calendar.end
     *
     * @mbggenerated
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.end
     *
     * @param end the value for man_calendar.end
     *
     * @mbggenerated
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.allDay
     *
     * @return the value of man_calendar.allDay
     *
     * @mbggenerated
     */
    public Boolean getAllday() {
        return allday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.allDay
     *
     * @param allday the value for man_calendar.allDay
     *
     * @mbggenerated
     */
    public void setAllday(Boolean allday) {
        this.allday = allday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.color
     *
     * @return the value of man_calendar.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.color
     *
     * @param color the value for man_calendar.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.backgroundColor
     *
     * @return the value of man_calendar.backgroundColor
     *
     * @mbggenerated
     */
    public String getBackgroundcolor() {
        return backgroundcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.backgroundColor
     *
     * @param backgroundcolor the value for man_calendar.backgroundColor
     *
     * @mbggenerated
     */
    public void setBackgroundcolor(String backgroundcolor) {
        this.backgroundcolor = backgroundcolor == null ? null : backgroundcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.borderColor
     *
     * @return the value of man_calendar.borderColor
     *
     * @mbggenerated
     */
    public String getBordercolor() {
        return bordercolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.borderColor
     *
     * @param bordercolor the value for man_calendar.borderColor
     *
     * @mbggenerated
     */
    public void setBordercolor(String bordercolor) {
        this.bordercolor = bordercolor == null ? null : bordercolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.textColor
     *
     * @return the value of man_calendar.textColor
     *
     * @mbggenerated
     */
    public String getTextcolor() {
        return textcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.textColor
     *
     * @param textcolor the value for man_calendar.textColor
     *
     * @mbggenerated
     */
    public void setTextcolor(String textcolor) {
        this.textcolor = textcolor == null ? null : textcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_calendar.status
     *
     * @return the value of man_calendar.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_calendar.status
     *
     * @param status the value for man_calendar.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_calendar
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", ownerid=").append(ownerid);
        sb.append(", start=").append(start);
        sb.append(", end=").append(end);
        sb.append(", allday=").append(allday);
        sb.append(", color=").append(color);
        sb.append(", backgroundcolor=").append(backgroundcolor);
        sb.append(", bordercolor=").append(bordercolor);
        sb.append(", textcolor=").append(textcolor);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}