package com.rzq.gpms.api.tree.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.rzq.gpms.api.tree.domain.Tree;
import com.rzq.gpms.api.tree.domain.TreeCriteria;

public interface TreeMapper {
	/**
	 * 
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int countByExample(TreeCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int deleteByExample(TreeCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int insert(Tree record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int insertSelective(Tree record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	List<Tree> selectByExampleWithRowbounds(TreeCriteria example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	List<Tree> selectByExample(TreeCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	Tree selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Tree record,
			@Param("example") TreeCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Tree record,
			@Param("example") TreeCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Tree record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_tree
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Tree record);
}