package com.rzq.gpms.api.message.domain;

import java.io.Serializable;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_message.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_message.transforttype
     *
     * @mbggenerated
     */
    private String transforttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_message.receiverid
     *
     * @mbggenerated
     */
    private Integer receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_message.responserid
     *
     * @mbggenerated
     */
    private Integer responserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_message.id
     *
     * @return the value of man_message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_message.id
     *
     * @param id the value for man_message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_message.transforttype
     *
     * @return the value of man_message.transforttype
     *
     * @mbggenerated
     */
    public String getTransforttype() {
        return transforttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_message.transforttype
     *
     * @param transforttype the value for man_message.transforttype
     *
     * @mbggenerated
     */
    public void setTransforttype(String transforttype) {
        this.transforttype = transforttype == null ? null : transforttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_message.receiverid
     *
     * @return the value of man_message.receiverid
     *
     * @mbggenerated
     */
    public Integer getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_message.receiverid
     *
     * @param receiverid the value for man_message.receiverid
     *
     * @mbggenerated
     */
    public void setReceiverid(Integer receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_message.responserid
     *
     * @return the value of man_message.responserid
     *
     * @mbggenerated
     */
    public Integer getResponserid() {
        return responserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_message.responserid
     *
     * @param responserid the value for man_message.responserid
     *
     * @mbggenerated
     */
    public void setResponserid(Integer responserid) {
        this.responserid = responserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_message.content
     *
     * @return the value of man_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_message.content
     *
     * @param content the value for man_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transforttype=").append(transforttype);
        sb.append(", receiverid=").append(receiverid);
        sb.append(", responserid=").append(responserid);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}