package com.rzq.gpms.api.plan.dao;

import com.rzq.gpms.api.plan.domain.Plan;
import com.rzq.gpms.api.plan.domain.PlanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int countByExample(PlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int deleteByExample(PlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    List<Plan> selectByExampleWithRowbounds(PlanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    List<Plan> selectByExample(PlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    Plan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Plan record, @Param("example") PlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Plan record, @Param("example") PlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Plan record);
}