package com.rzq.gpms.api.message.dao;

import com.rzq.gpms.api.message.domain.Message;
import com.rzq.gpms.api.message.domain.MessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int countByExample(MessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int deleteByExample(MessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    List<Message> selectByExampleWithRowbounds(MessageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    List<Message> selectByExample(MessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Message record);
}